sudo: required
services:
  - docker

before_install:
  - docker build -t auaden/docker-react -f Dockerfile.dev .

script:
  - docker run auaden/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-1'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-1-037203025666'
  path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
